### ISSUE TITLE
[1.12.2] XP Chicken Drops Config Not Working

### ISSUE THREAD

**Issue by MokahTGS** [GenDeathrow/MoreChickens#47]
I'm trying to change the XP Chicken drops in the config and it does not seem to be working or listening to what is put into the config.

Current config setup is this:

  "morechickens:xpchicken": {
    "Name": "xpChicken",
    "Is Enabled": true,
    "Lay Coefficient": 1.0,
    "Lay Item": "<actuallyadditions:item_solidified_experience>",
    "Drop Item": "<actuallyadditions:item_solidified_experience>",
    "Spawn Type": "NONE",
    "Parent 1": "chickens:emeraldchicken",
    "Parent 2": "chickens:greenchicken"
  },

I am absolutely certain the item name is correct.  The chickens just aren't producing this item for some reason.

**Comment by GenDeathrow** [comment]
Im sure its correct but the problem is when the items get registered for chickens. Im currently working on an update to the item system for chickens/more chickens. Im hoping the update will be this week. but it will fix your problem.  But any changes you made it may not load them correctly will see. But the new system will also support nbt data and be easier to read.

**Comment by MokahTGS** [comment]
Good to hear.  Let me know when it gets changed.

**Comment by GenDeathrow** [comment]
Ive uploaded alpha versions of the new item handling system(Chickens & MoreChickens). Let me know if this new system works better for you.. it will convert your old config over. Now it will prolly overwrite your old configs though. so use a backup.
